### PR TITLE
Fix setting of the application/json header when the request/response body is passed as an object

### PR DESCRIPTION
**Pull request by papandreou**
Also, fix passing of the method as part of the `url` property.

### CODE REVIEW

**Comment by gustavnikolaj** [comment]
Except from the lint errors it looks great. :-)

It seems to be mostly indentation issues - we have an editorconfig file set up in the project - maybe your missing that plugin in the editor?

**Comment by papandreou** [comment]
Seems like I am, thanks for the hint. Still getting set up :)

I'll fix it up and add another feature (`request.query`), then ping you back.

**Comment by papandreou** [comment]
@gustavnikolaj, done for now :)

**Comment by papandreou** [comment]
I'm aware that the `query` thing has to go into unexpected-messy and messy in order to support `expect.it` in the spec. I'll work on that later.

**Comment by gustavnikolaj** [comment]
LGTM :+1:

**Pull request merged**
